# Generated by Django 3.2.1 on 2021-05-30 13:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('banco', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('release_date_of', models.DateField()),
                ('posted_value', models.BigIntegerField()),
                ('description', models.CharField(max_length=255)),
                ('id_bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='banco.banksusers')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
